"""migrate

Revision ID: df11fe9dfa0f
Revises: 
Create Date: 2018-09-15 14:51:58.744714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df11fe9dfa0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'category_id')
    # ### end Alembic commands ###
